name: Deploy .NET Core

on:
  push:
    branches: [ main ]
    paths-ignore:
    - ".github/workflows/**"
    - "*.yml"
env:
  WEB: ''
  
jobs:
  deployInfra:
    name: deployInfra
    runs-on: ubuntu-18.04
    steps:
    
    - uses: actions/checkout@v2
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure CLI Action
      uses: Azure/cli@1.0.4
      with:
        # Specify the script here
        inlineScript: |
            az group create -l westeurope -n TailwindTraders
            WEB=$(az deployment group create -g deleteme -f ./Deploy/main.bicep)
            WEB=$(echo $WEB | jq -re .properties.outputs.web.value)
            echo "WEB=$(echo $WEB" >> $GITHUB_ENV
    
  deployStaging:
    environment:
      name: Staging
      url: 'http://${{ env.WEB }}-staging.azurewebsites.net'
    needs: deployInfra
    runs-on: ubuntu-18.04
    env:
      CI: ""

    steps:
    
    - uses: actions/checkout@v2  
    - name: Microsoft Teams Deploy Card
      uses: toko-bifrost/ms-teams-deploy-card@3.1.2
      if: always()
      with:
        webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
        github-token: ${{ secrets.GH_TOKEN }} 
        environment: staging
        card-layout-start: complete
        card-layout-exit: cozy
        show-on-exit: true
        view-status-action-text: View staging deploy status
        custom-actions: |
          - text: View Staging Website
            url: "http://tailwindtradersng327aivqywig-staging.azurewebsites.net"


    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ttacrng327aivqywig
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ttacrng327aivqywig.azurecr.io


    - run: |
        cd Source/Tailwind.Traders.Web
        docker build . -t ttacrng327aivqywig.azurecr.io/tailwindtraders-app:${{ github.sha }}
        docker push ttacrng327aivqywig.azurecr.io/tailwindtraders-app:${{ github.sha }}
    - name: Azure authentication
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
  
    - name: Deploy image to staging slot
      uses: Azure/webapps-deploy@v2
      with:
        app-name: tailwindtradersng327aivqywig
        slot-name: staging
        images: ttacrng327aivqywig.azurecr.io/tailwindtraders-app:${{ github.sha }}
  
  deployProduction:
    environment:
      name: Production
      url: 'http://tailwindtradersng327aivqywig.azurewebsites.net'
    needs: deployStaging
    runs-on: ubuntu-18.04
    env: 
      CI: ""
      
    steps:
    - uses: actions/checkout@v2
  
    - name: Microsoft Teams Deploy Card
      uses: toko-bifrost/ms-teams-deploy-card@3.1.2
      if: always()
      with:
        webhook-uri: ${{ secrets.TEAMS_WEBHOOK }}
        github-token: ${{ secrets.GH_TOKEN }} 
        environment: production
        card-layout-start: complete
        card-layout-exit: cozy
        show-on-exit: true
        view-status-action-text: View prod deployment status
        custom-actions: |
          - text: View Production Website
            url: "http://tailwindtradersng327aivqywig.azurewebsites.net"

    - name: Azure authentication
      uses: azure/login@v1
      with:          
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
      
    - name: Swap staging to production
      run: |
        az webapp deployment slot swap --name tailwindtradersng327aivqywig --resource-group AAA-Azure-rg --slot staging --target-slot production

