name: .NET Core

on:
  push:
    branches: [ main ]
    paths-ignore:
    - ".github/workflows/**"
    - "*.yml"
  pull_request:
    branches: [ main ]
    paths-ignore:
    - ".github/workflows/**"
    - "*.yml"

jobs:
  build:

    runs-on: ubuntu-18.04
    env:
      CI: ""

    steps:

    - uses: actions/checkout@v2
   
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.x
   
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
   
    - name: Install dependencies
      run: dotnet restore ./Source/*.sln
   
    - name: Build
      run: dotnet build ./Source/*.sln --configuration Release --no-restore
   
    - name: Test
      run: dotnet test ./Source/*.sln --no-restore --verbosity normal
    
    - name: Publish
      run: dotnet publish ./Source/Tailwind.Traders.Web/Tailwind.Traders.Web.csproj -c Release -o './staging'
    
  deployStaging:
    environment: Staging
    name: DeployStaging
    needs: build
    runs-on: ubuntu-18.04
    env:
      CI: ""

    steps:

    - uses: actions/checkout@v2
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ttacrng327aivqywig
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ttacrng327aivqywig.azurecr.io


    - run: |
        cd Source/Tailwind.Traders.Web
        docker build . -t ttacrng327aivqywig.azurecr.io/tailwindtraders-app:${{ github.sha }} -t tailwindtraders-app
        docker push ttacrng327aivqywig.azurecr.io/tailwindtraders-app
  
  deployProduction:
    if: github.ref == 'refs/heads/main'
    environment: Production
    name: DeployProduction
    runs-on: ubuntu-18.04
    env: 
      CI: ""
      
    steps:
    - name: Azure authentication
      uses: azure/login@v1
      with:          
        creds: ${{ secrets.AZURE_CREDENTIALS  }}
      
    - name: Swap staging to production
      run: |
        az webapp deployment slot swap --name tailwindtradersng327aivqywig --resource-group AAA-Azure-rg --slot staging --target-slot production

    
